community-house/Controllers/FavouritesController.cs
using community_house.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace community_house.Controllers
{
    public class FavouritesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Houses");
        }

        public ActionResult Create(int houseID)
        {
            this.db.Favourites.Add(new Favourite { HouseID = houseID, UserId = db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id });

            this.db.SaveChanges();
            return RedirectToAction("Index", "Houses");
        }

        public ActionResult Delete(int houseID)
        {
            //this.db.Favourites.Remove(new Favourite { HouseID = houseID, UserId = db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id });
            var fav = this.db.Favourites.
                Where(h => h.HouseID == houseID).
                Where(z => z.UserId == db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id).FirstOrDefault();

            this.db.Favourites.Remove(fav);
            this.db.SaveChanges();

            return RedirectToAction("MyFavourites", "Houses");
        }
    }
}

community-house/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using community_house.Models;
using NeuralNetworkLibrary;

namespace community_house.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Houses
        public ActionResult MyFavourites()
        {
            var houses = from x in db.Favourites
                         join y in db.Houses on x.HouseID equals y.HouseID
                         join z in db.Users on x.UserId equals z.Id
                         where x.UserId.Equals(db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id)
                         select y;
            
            return View(houses.ToList());
        }

        // GET: Houses
        public ActionResult MyIndex()
        {

            IQueryable<House> houses = db.Houses.
                Include(h => h.User).
                Include(h => h.Pictures).
                Where(h => h.UserId == db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id);

            return View(houses.ToList());
        }

        // GET: Houses
        public ActionResult Index(string sortOrder, string searchStringCity, int searchStringMinPrice = 0, int searchStringMaxPrice = Int32.MaxValue)
        {
            IQueryable<House> houses = this.GetSortedHouses(sortOrder);

            this.ViewData = this.InitializeViewBagSortOrder(sortOrder);

            if (searchStringCity != null && searchStringCity != "")
            {
                houses = houses
                    .Where(x => x.City == searchStringCity);
                    
            }

            if (searchStringMinPrice != 0)
            {
                houses = houses.Where(x => (x.Price > searchStringMinPrice));

            }

            if (searchStringMaxPrice != Int32.MaxValue)
            {
                houses = houses.Where(x => (x.Price < searchStringMaxPrice));
            }
            
            return View(houses.ToList());
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // GET: Houses/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HouseID,UserId,Price,Area,City,Address")] House house, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Public/Images/") + file.FileName);                    
                }

                db.Houses.Add(house);
                db.SaveChanges();

                db.Pictures.Add(new Picture { FileName = file.FileName, HouseID = house.HouseID });
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HouseID,UserId,Price,Area,City,Address")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IQueryable<House> GetSortedHouses(string sortOrder = "cityasc")
        {
            IQueryable<House> houses = db.Houses.Include(h => h.User).Include(h => h.Pictures).Include(h => h.Favourites);
            
            if (sortOrder == "cityasc") {
                return houses.OrderBy(s => s.City);
            }

            if (sortOrder == "citydesc") {
                return houses.OrderByDescending(s => s.City);
            }

            if (sortOrder == "areaasc") {
                return houses.OrderBy(s => s.Area);
            }

            if (sortOrder == "areadisc") {
                return houses.OrderByDescending(s => s.Area);
            }

            if (sortOrder == "priceasc") {
                return houses.OrderBy( s => s.Price);
            }

            if (sortOrder == "pricedesc") {
                return houses.OrderByDescending(s => s.Price);
            }

            if (sortOrder == "emailasc") {
                return houses.OrderBy(s => s.User.Email);
            }
            if (sortOrder == "emaildesc") {
                return houses.OrderByDescending(s => s.User.Email);
            }

            return houses;
        }

        private ViewDataDictionary InitializeViewBagSortOrder(string sortOrder)
        {
            ViewDataDictionary d = new ViewDataDictionary();

            if (sortOrder == null || sortOrder == "")
            {
                sortOrder = "priceasc";
            }

            if (sortOrder == "cityasc")
            {
                d["city"] = "desc";
            }
            else
            {
                d["city"] = "asc";
            }


            if (sortOrder == "areaasc")
            {
                d["area"] = "desc";
            }
            else
            {
                d["area"] = "asc";
            }

            if (sortOrder == "priceasc")
            {
                d["price"] = "desc";
            }
            else
            {
                d["price"] = "asc";
            }

            if (sortOrder == "emailasc")
            {
                d["email"] = "desc";
            }
            else
            {
                d["email"] = "asc";
            }

            return d;
        }
    }
}

community-house/Views/Houses/Create.cshtml
@model community_house.Models.House

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Houses", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>House</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.Hidden("UserID", community_house.Models.ApplicationDbContext.Create().Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <input id="ImagePath" title="Upload a product image" type="file" name="file" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

community-house/Views/Houses/Delete.cshtml
@model community_house.Models.House

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>House</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

community-house/Views/Houses/Details.cshtml
@model community_house.Models.House

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>House</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HouseID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

community-house/Views/Houses/Edit.cshtml
@model community_house.Models.House

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>House</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HouseID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

community-house/Views/Houses/Index.cshtml
@model IEnumerable<community_house.Models.House>

@{
    ViewBag.Title = "All Houses";
}

<h2>All Houses</h2>

<div class="row">
    <div class="col-sm-6">  

        @using (Html.BeginForm("Index", "Houses", FormMethod.Get))
        {
                <div class="row">
                    <div class="col-sm-12">
                        <label class="control-label"> City </label>
                        @Html.TextBox("SearchStringCity", null, new { @placeholder = "Search for a city...", @class = "form-control" }) <br />
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        <label class="control-label"> Min Price </label>
                        @Html.TextBox("SearchStringMinPrice", null, new { @placeholder = "Min Price...", @class = "form-control" }) <br />
                    </div>

                    <div class="col-sm-4">
                        <label class="control-label"> Max Price </label>
                        @Html.TextBox("SearchStringMaxPrice", null, new { @placeholder = "Price...", @class = "form-control" }) <br />
                    </div>
                </div>


                <input type="submit" value="Filter" class=" btn btn-success "/>
        } 

        @if (Model.Count() == 0)
        {
            <h1> No houses were found! </h1>
        }
        
        else {

            <table class="table">
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        @Html.ActionLink("City", "Index", new { sortOrder = "city" + ViewData["city"] })
                    </th>
                    <th>                    
                        @Html.ActionLink("Area", "Index", new { sortOrder = "area" + ViewData["area"] })
                    </th>
                    <th>
                        @Html.ActionLink("Price", "Index", new { sortOrder = "price" + ViewData["price"] })
                    </th>
                    <th>
                        @Html.ActionLink("Email", "Index", new { sortOrder = "email" + ViewData["email"] })
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="~/Public/Images/@item.Pictures.FirstOrDefault().FileName" width="100" height="100" alt="Image not Found!" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.City)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Area)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)$
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Email)
                        </td>
                        <td>
                            @if (Request.IsAuthenticated) 
                            { 
                                
                                if ( item.Favourites.Where(a => a.User.Email.Equals(User.Identity.Name)).Count() == 0 )
                                {
                                    @Html.ActionLink("Favorite", "Create", "Favourites", new { houseID = item.HouseID }, null)
                                
                                }
                                else
                                {
                                    <p>Already in Favorites</p>
                                }
                            }
                        </td>
                    </tr>
                }

            </table>
        }
    </div>
</div>

community-house/Views/Houses/MyFavourites.cshtml
@model IEnumerable<community_house.Models.House>

@{
    ViewBag.Title = "MyIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>MyIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.ActionLink("Price", "MyIndex", new { sortOrder = "price" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="~/Public/Images/@item.Pictures.FirstOrDefault().FileName" width="100" height="100" alt="Alternate Text" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink("Unfavourite", "Delete", "Favourites", new { houseID = item.HouseID }, null)
            </td>
        </tr>
    }

</table>

community-house/Views/Houses/MyIndex.cshtml
@model IEnumerable<community_house.Models.House>

@{
    ViewBag.Title = "MyIndex";
}

<h2>MyIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.ActionLink("Price", "MyIndex", new { sortOrder = "price" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="~/Public/Images/@item.Pictures.FirstOrDefault().FileName" width="100" height="100" alt="Alternate Text" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HouseID }) |
            @Html.ActionLink("Details", "Details", new { id=item.HouseID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.HouseID })
        </td>
    </tr>
}

</table>