community-house/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace community_house.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

community-house/Controllers/HousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using community_house.Models;
using NeuralNetworkLibrary;

namespace community_house.Controllers
{
    public class HousesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Houses
        public ActionResult MyFavourites()
        {
            var houses = from x in db.Favourites
                         join y in db.Houses on x.HouseID equals y.HouseID
                         join z in db.Users on x.UserId equals z.Id
                         where x.UserId.Equals(db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id)
                         select y;
            
            return View(houses.ToList());
        }

        // GET: Houses
        public ActionResult MyIndex()
        {

            IQueryable<House> houses = db.Houses.
                Include(h => h.User).
                Include(h => h.Pictures).
                Where(h => h.UserId == db.Users.FirstOrDefault(s => s.Email == User.Identity.Name).Id);

            return View(houses.ToList());
        }

        // GET: Houses
        public ActionResult Index(string sortOrder, string searchStringCity, int searchStringMinPrice = 0, int searchStringMaxPrice = Int32.MaxValue)
        {
            IQueryable<House> houses = this.GetSortedHouses(sortOrder);

            this.ViewData = this.InitializeViewBagSortOrder(sortOrder);

            if (searchStringCity != null && searchStringCity != "")
            {
                houses = houses
                    .Where(x => x.City == searchStringCity);
                    
            }

            if (searchStringMinPrice != 0)
            {
                houses = houses.Where(x => (x.Price > searchStringMinPrice));

            }

            if (searchStringMaxPrice != Int32.MaxValue)
            {
                houses = houses.Where(x => (x.Price < searchStringMaxPrice));
            }
            
            return View(houses.ToList());
        }

        // GET: Houses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // GET: Houses/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Houses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HouseID,UserId,Price,Area,City,Address")] House house, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    file.SaveAs(HttpContext.Server.MapPath("~/Public/Images/") + file.FileName);                    
                }

                db.Houses.Add(house);
                db.SaveChanges();

                db.Pictures.Add(new Picture { FileName = file.FileName, HouseID = house.HouseID });
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // GET: Houses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // POST: Houses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HouseID,UserId,Price,Area,City,Address")] House house)
        {
            if (ModelState.IsValid)
            {
                db.Entry(house).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", house.UserId);
            return View(house);
        }

        // GET: Houses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            House house = db.Houses.Find(id);
            if (house == null)
            {
                return HttpNotFound();
            }
            return View(house);
        }

        // POST: Houses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            House house = db.Houses.Find(id);
            db.Houses.Remove(house);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IQueryable<House> GetSortedHouses(string sortOrder = "cityasc")
        {
            IQueryable<House> houses = db.Houses.Include(h => h.User).Include(h => h.Pictures).Include(h => h.Favourites);
            
            if (sortOrder == "cityasc") {
                return houses.OrderBy(s => s.City);
            }

            if (sortOrder == "citydesc") {
                return houses.OrderByDescending(s => s.City);
            }

            if (sortOrder == "areaasc") {
                return houses.OrderBy(s => s.Area);
            }

            if (sortOrder == "areadisc") {
                return houses.OrderByDescending(s => s.Area);
            }

            if (sortOrder == "priceasc") {
                return houses.OrderBy( s => s.Price);
            }

            if (sortOrder == "pricedesc") {
                return houses.OrderByDescending(s => s.Price);
            }

            if (sortOrder == "emailasc") {
                return houses.OrderBy(s => s.User.Email);
            }
            if (sortOrder == "emaildesc") {
                return houses.OrderByDescending(s => s.User.Email);
            }

            return houses;
        }

        private ViewDataDictionary InitializeViewBagSortOrder(string sortOrder)
        {
            ViewDataDictionary d = new ViewDataDictionary();

            if (sortOrder == null || sortOrder == "")
            {
                sortOrder = "priceasc";
            }

            if (sortOrder == "cityasc")
            {
                d["city"] = "desc";
            }
            else
            {
                d["city"] = "asc";
            }


            if (sortOrder == "areaasc")
            {
                d["area"] = "desc";
            }
            else
            {
                d["area"] = "asc";
            }

            if (sortOrder == "priceasc")
            {
                d["price"] = "desc";
            }
            else
            {
                d["price"] = "asc";
            }

            if (sortOrder == "emailasc")
            {
                d["email"] = "desc";
            }
            else
            {
                d["email"] = "asc";
            }

            return d;
        }
    }
}

community-house/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

community-house/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

community-house/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Community Houses</h1>
    <p class="lead">Community Houses is a free web real estate platform.</p>
    @Html.ActionLink("Pick a house »", "Index", "Houses", new { @class = "btn btn btn-primary btn-lg" })
</div>

<div class="row">
    
    <div class="col-md-4">
        <h2>Getting started!</h2>
        <p>
            You can get started by creating an account and then " ‘Why don’t you like to be touched?’ I whisper, staring up into soft gray eyes. ‘Because I’m fifty shades of fucked up, Anastasia.’ ” setting a price range or picking the city you would like to live in!
        </p>
        @Html.ActionLink("Learn More »", "Index", "Houses", new { @class = "btn btn-default" })
    </div>

    <div class="col-md-4">
        <h2>Create your own account!</h2>
        <p> Register your own account if you “The heart is capable of sacrifice. So is the vagina. The heart is able to forgive and repair. It can change it's shape to let us in. It can expand to let us out. So can the vagina. It can ache for us and stretch for us, die for us and bleed and bleed us into this difficult, wondrous world. So can the vagina. I was there in the room. I remeber.” don't want to pay moneyz to real estate angent with smelly feet and go </p>
        @Html.ActionLink("Register NOW! »", "Register", "Account", new { @class = "btn btn-default" })
    </div>

    <div class="col-md-4">
        <h2>Add houses to your favorites!</h2>
        <p> Using our platform you can search through various houses and whenever you stumble upon ones you like - add them to your favorites and come back to them again!</p>
        @Html.ActionLink("Log in »", "Login", "Account", new { @class = "btn btn-default" })
    </div>
</div>